# Generated by Django 6.0.5 on 2026-05-11 00:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=16, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telepon', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Poli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(choices=[('umum', 'Poli Umum'), ('gigi', 'Poli Gigi'), ('mata', 'Poli Mata'), ('anak', 'Poli Anak')], max_length=10, unique=True)),
                ('nama', models.CharField(max_length=50)),
                ('prefix', models.CharField(max_length=5)),
                ('counter', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Antrian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomor_antrian', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('waiting', 'Menunggu'), ('done', 'Selesai')], default='waiting', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue_app.pasien')),
                ('poli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue_app.poli')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pemeriksaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosa', models.TextField(default='Belum diisi')),
                ('tindakan', models.TextField(default='Belum diisi')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('antrian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='queue_app.antrian')),
            ],
        ),
    ]
