# Generated by Django 5.2.12 on 2026-05-28 20:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=16, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telepon', models.CharField(blank=True, max_length=15)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(choices=[('umum', 'Poli Umum'), ('gigi', 'Poli Gigi'), ('mata', 'Poli Mata'), ('anak', 'Poli Anak')], max_length=10, unique=True)),
                ('nama', models.CharField(max_length=50)),
                ('prefix', models.CharField(max_length=5)),
                ('counter', models.IntegerField(default=1)),
                ('kuota_harian', models.IntegerField(default=50)),
                ('durasi_rata_rata', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateResep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_template', models.CharField(max_length=100)),
                ('diagnosa_default', models.TextField(blank=True)),
                ('tindakan_default', models.TextField(blank=True)),
                ('resep_default', models.TextField(blank=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Antrian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomor_antrian', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('waiting', 'Menunggu'), ('called', 'Dipanggil'), ('done', 'Selesai'), ('skipped', 'Dilewati')], default='waiting', max_length=10)),
                ('prioritas', models.IntegerField(choices=[(0, 'Normal'), (1, 'Prioritas'), (2, 'Darurat')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue_app.pasien')),
                ('poli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue_app.poli')),
            ],
            options={
                'ordering': ['-prioritas', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pemeriksaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosa', models.TextField(default='')),
                ('tindakan', models.TextField(default='')),
                ('resep_obat', models.TextField(default='')),
                ('catatan', models.TextField(blank=True, default='')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('antrian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='queue_app.antrian')),
            ],
        ),
    ]
